# Generated by Django 4.2.7 on 2023-11-08 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="cusomter",
            new_name="cusomter_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="image_url",
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="image_url",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="date",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
