# Generated by Django 4.2.7 on 2023-11-20 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_rename_cusomter_invoice_cusomter_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="cusomter_id",
            new_name="customer_id",
        ),
    ]
