# Generated by Django 4.2.7 on 2023-11-21 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_rename_cusomter_id_invoice_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.customer",
            ),
        ),
    ]
