# Generated by Django 4.2.7 on 2023-11-21 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_invoice_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer_id",
            field=models.ForeignKey(
                default="3958dc9e-742f-4377-85e9-fec4b6a6442a",
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.customer",
            ),
            preserve_default=False,
        ),
    ]
